# Generated by Django 3.1.7 on 2021-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2021-04-29 11:56:56', verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
