# Generated by Django 3.1.7 on 2021-04-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210429_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientuser',
            old_name='age',
            new_name='birthday',
        ),
    ]
