# Generated by Django 3.1.7 on 2021-04-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210426_2345'),
        ('patient', '0006_auto_20210429_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientURLPermissions',
            new_name='PatientURLPermission',
        ),
    ]
