# Generated by Django 3.1.7 on 2021-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20210429_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='patient_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='就诊号'),
        ),
    ]
