# Generated by Django 3.1.7 on 2021-05-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpatient', '0004_auto_20210509_2034'),
        ('his', '0006_auto_20210509_2222'),
        ('patient', '0008_auto_20210508_2307'),
        ('pharmacy', '0002_auto_20210509_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(auto_created=True, editable=False, verbose_name='手术日期')),
                ('opration_id', models.PositiveIntegerField(help_text='局部编号：每个医生-患者之间进行的第几场手术', verbose_name='手术编号')),
                ('operation_level', models.PositiveIntegerField(choices=[(1, '一级手术'), (2, '二级手术'), (3, '三级手术'), (4, '四级手术')], default=1, verbose_name='手术等级')),
                ('operation_name', models.CharField(max_length=40, verbose_name='手术名称')),
                ('operation_result', models.CharField(blank=True, max_length=20, verbose_name='手术结果')),
                ('operation_duration', models.TimeField(blank=True, null=True, verbose_name='手术持续时间')),
                ('operation_recover', models.CharField(blank=True, max_length=10, verbose_name='预后结果')),
                ('payment_status', models.BooleanField(default=False, verbose_name='缴费状态')),
                ('registration_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatient.registrationinfo', verbose_name='挂号信息')),
            ],
            options={
                'verbose_name': '手术信息',
                'verbose_name_plural': '手术信息',
                'unique_together': {('registration_info', 'opration_id')},
            },
        ),
        migrations.CreateModel(
            name='NarcoticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narcotic_set', related_query_name='narcotics', to='his.staff', verbose_name='麻醉师')),
                ('medicin_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narcotic_set', related_query_name='narcotics', to='pharmacy.medicineinfo', verbose_name='麻醉药品信息')),
                ('operation_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narcotic_set', related_query_name='narcotics', to='inpatient.operationinfo', verbose_name='手术信息')),
            ],
            options={
                'verbose_name': '麻醉信息',
                'verbose_name_plural': '麻醉信息',
            },
        ),
        migrations.CreateModel(
            name='HospitalRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_created=True, editable=False, verbose_name='入院日期')),
                ('bed_id', models.PositiveIntegerField(verbose_name='床位号')),
                ('care_level', models.PositiveIntegerField(choices=[(1, '一级护理'), (2, '二级护理'), (3, '三级护理'), (4, '四级护理')], default=3, verbose_name='护理级别')),
                ('duration', models.PositiveIntegerField(null=True, verbose_name='住院天数')),
                ('kin_phone', models.CharField(max_length=11, verbose_name='家属电话')),
                ('discharge_status', models.BooleanField(default=False, verbose_name='即将出院状态')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='his.inpatientarea', verbose_name='所属病区')),
                ('registration_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outpatient.registrationinfo', verbose_name='挂号信息')),
            ],
            options={
                'verbose_name': '入院登记信息',
            },
        ),
        migrations.CreateModel(
            name='NursingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursing_date', models.DateField(auto_created=True, editable=False, verbose_name='护理时间')),
                ('systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='体温')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('medical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_record_set', related_query_name='nursing_records', to='his.staff', verbose_name='责任护士')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_record_set', related_query_name='nursing_records', to='patient.patientuser', verbose_name='患者')),
            ],
            options={
                'verbose_name': '护理记录',
                'verbose_name_plural': '护理记录',
                'unique_together': {('medical_staff', 'patient', 'nursing_date')},
            },
        ),
    ]
