# Generated by Django 3.1.7 on 2021-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_auto_20210516_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narcoticinfo',
            old_name='medicin_info',
            new_name='medicine_info',
        ),
    ]
