# Generated by Django 3.1.7 on 2021-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
        ('inpatient', '0002_auto_20210529_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregistration',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reg_set', related_query_name='hospital_regs', to='his.inpatientarea', verbose_name='所属病区'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='bed_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='床位号'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='discharge_status',
            field=models.PositiveIntegerField(choices=[(0, '未出院'), (1, '即将出院'), (2, '已出院')], default=0, verbose_name='出院状态'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='kin_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='家属电话'),
        ),
        migrations.AlterField(
            model_name='hospitalregistration',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='入院日期'),
        ),
    ]
