# Generated by Django 3.1.7 on 2021-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_auto_20210531_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregistration',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='缴费状态'),
        ),
    ]
