# Generated by Django 3.1.7 on 2021-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='item_type',
            field=models.IntegerField(choices=[(0, '挂号'), (1, '检查检验'), (2, '手术'), (3, '处方'), (4, '出院结算')], help_text='不同项目类型对应着不同的表，例如检查检验表、手术信息表、处方表等。', verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='HIS系统创建订单的时间。', verbose_name='订单时间'),
        ),
    ]
