# Generated by Django 3.1.7 on 2021-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepurchase',
            name='purchase_date',
            field=models.DateField(verbose_name='采购日期'),
        ),
    ]
