# Generated by Django 3.1.7 on 2021-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineinfo',
            options={'verbose_name': '药品信息', 'verbose_name_plural': '药品信息'},
        ),
        migrations.AlterModelOptions(
            name='medicinepurchase',
            options={'verbose_name': '药品采购记录', 'verbose_name_plural': '药品采购记录'},
        ),
    ]
