# Generated by Django 3.1.7 on 2021-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20210509_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='shelf_day',
            field=models.PositiveIntegerField(default=0, verbose_name='保质期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinepurchase',
            name='batch_num',
            field=models.PositiveIntegerField(default=0, verbose_name='批次编号'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='medicineinfo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='medicinepurchase',
            unique_together={('medicine_info', 'batch_num')},
        ),
        migrations.RemoveField(
            model_name='medicineinfo',
            name='batch_num',
        ),
        migrations.RemoveField(
            model_name='medicineinfo',
            name='overdue_date',
        ),
    ]
