# Generated by Django 3.1.7 on 2021-04-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlpermission',
            name='perm_group',
        ),
        migrations.DeleteModel(
            name='PermGroup',
        ),
    ]
