# Generated by Django 3.1.7 on 2021-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsmixin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='用户所属的用户组，用户能够获取所属用户组的全部权限。', related_name='user_set', related_query_name='user', to='rbac.UserGroup', verbose_name='用户组'),
        ),
    ]
