# Generated by Django 3.1.7 on 2021-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='用户组所拥有的角色，用户组能够获取所拥有角色的全部权限。', related_name='usergroup_set', related_query_name='usergroups', to='rbac.Role', verbose_name='角色'),
        ),
    ]
