# Generated by Django 3.1.7 on 2021-03-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permgroup_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permgroup',
            options={'verbose_name': '权限组表', 'verbose_name_plural': '权限组表'},
        ),
    ]
