# Generated by Django 3.1.7 on 2021-04-23 06:05

import django.core.validators
from django.db import migrations, models
import rbac.models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210423_1356'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('objects', rbac.models.UserInfoManager()),
            ],
        ),
        migrations.AlterField(
            model_name='permissionsmixin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='超级用户具有全部权限。', verbose_name='超级用户'),
        ),
        migrations.AlterField(
            model_name='permissionsmixin',
            name='url_permissions',
            field=models.ManyToManyField(blank=True, help_text='该用户具有的所有URL访问权限。', related_name='urlperm_set', related_query_name='urlperm', to='rbac.URLPermission', verbose_name='URL访问权限'),
        ),
        migrations.AlterField(
            model_name='urlpermission',
            name='codename',
            field=models.CharField(help_text='简要概括URL访问权限作用的对象，建议使用英文单词和下划线。', max_length=64, verbose_name='权限代码'),
        ),
        migrations.AlterField(
            model_name='urlpermission',
            name='name',
            field=models.CharField(help_text='URL访问权限的名称。', max_length=255, unique=True, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='urlpermission',
            name='url',
            field=models.CharField(help_text='用于匹配指定URL的正则表达式。', max_length=128, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(help_text='科室、部门或项目组名称。', max_length=32, unique=True, verbose_name='用户组名称'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='ug_id',
            field=models.IntegerField(help_text='用户组编号，取值范围为 1 ~ Inf。', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='用户组编号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='决定该用户是否为活动账户。', verbose_name='活动账户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='决定该用户是否能够访问 /admin 页面。', verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(help_text='以 6 位数字的工号作为登录账户名。', max_length=6, unique=True, verbose_name='登录账号'),
        ),
    ]
