# Generated by Django 3.1.7 on 2021-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20210423_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='url_permissions',
            field=models.ManyToManyField(blank=True, help_text='用户组具有的全部URL访问权限。', to='rbac.URLPermission', verbose_name='URL访问权限'),
        ),
    ]
