# Generated by Django 3.1.7 on 2021-04-23 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_usergroup_url_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permissionsmixin',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='用户所拥有的角色，用户能够获取所拥有角色的全部权限。', related_name='user_set', related_query_name='user', to='rbac.Role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='role',
            name='url_permissions',
            field=models.ManyToManyField(blank=True, help_text='该角色拥有的URL访问权限', related_name='role_set', related_query_name='role', to='rbac.URLPermission', verbose_name='URL访问权限'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='url_permissions',
            field=models.ManyToManyField(blank=True, help_text='用户组具有的全部URL访问权限。', related_name='usergroup_set', related_query_name='usergroup', to='rbac.URLPermission', verbose_name='URL访问权限'),
        ),
    ]
