# Generated by Django 3.1.7 on 2021-05-09 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('his', '0004_auto_20210509_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItemType',
            fields=[
                ('inspect_type_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='检验项目类型编号')),
                ('inspect_type_name', models.CharField(max_length=30, verbose_name='检验项目类型名称')),
            ],
            options={
                'verbose_name': '检验项目类型',
                'verbose_name_plural': '检验项目类型',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('inspect_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='检验项目编号')),
                ('inspect_name', models.CharField(max_length=30, verbose_name='检验项目名称')),
                ('inspect_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='检验价格')),
                ('inspect_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.testitemtype', verbose_name='检验项目类型')),
            ],
            options={
                'verbose_name': '检验项目',
                'verbose_name_plural': '检验项目',
            },
        ),
        migrations.CreateModel(
            name='PatientTestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(auto_created=True, editable=False, verbose_name='开具时间')),
                ('test_id', models.PositiveIntegerField(help_text='A病人第X次挂号的第i项检验', verbose_name='检验序号')),
                ('test_results', models.TextField(blank=True, max_length=400, verbose_name='检验结果')),
                ('payment_status', models.BooleanField(default=False, verbose_name='缴费状态')),
                ('handle_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='his.staff', verbose_name='责任人')),
            ],
            options={
                'verbose_name': '患者检验项目',
                'verbose_name_plural': '患者检验项目',
            },
        ),
    ]
