# Generated by Django 3.1.7 on 2021-05-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpatient', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttestitem',
            name='registration_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='outpatient.registrationinfo', verbose_name='挂号信息'),
        ),
        migrations.AddField(
            model_name='patienttestitem',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='laboratory.testitem', verbose_name='检验项目'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttestitem',
            unique_together={('registration_info', 'test_id', 'test_item')},
        ),
    ]
