# Generated by Django 3.1.7 on 2021-06-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpatient', '0001_initial'),
        ('his', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttestitem',
            name='handle_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='his.staff', verbose_name='负责医师'),
        ),
        migrations.AddField(
            model_name='patienttestitem',
            name='registration_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='outpatient.registrationinfo', verbose_name='挂号信息'),
        ),
        migrations.AddField(
            model_name='patienttestitem',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='laboratory.testitem', verbose_name='检验项目'),
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_info_set', related_query_name='equipment_infos', to='laboratory.equipmenttypeinfo', verbose_name='设备类型'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttestitem',
            unique_together={('registration_info', 'test_id')},
        ),
    ]
