# Generated by Django 3.1.7 on 2021-05-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20210509_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypeInfo',
            fields=[
                ('eq_type_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='设备类型编号')),
                ('eq_type_name', models.CharField(max_length=100, verbose_name='设备类型名称')),
            ],
            options={
                'verbose_name': '设备类型信息',
                'verbose_name_plural': '设备类型信息',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInfo',
            fields=[
                ('equipment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='设备全局编号')),
                ('equipment_model', models.CharField(max_length=20, verbose_name='设备型号')),
                ('start_using', models.DateField(verbose_name='启用日期')),
                ('lifetime', models.PositiveIntegerField(verbose_name='理论使用寿命')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_info_set', related_query_name='equipment_infos', to='laboratory.equipmenttypeinfo', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='EquipmentPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_created=True, editable=False, verbose_name='采购时间')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='采购数量')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_purchase_set', related_query_name='equipment_purchases', to='laboratory.equipmentinfo', verbose_name='设备信息')),
            ],
            options={
                'verbose_name': '设备采购记录',
                'verbose_name_plural': '设备采购记录',
                'unique_together': {('equipment', 'purchase_date')},
            },
        ),
    ]
