# Generated by Django 3.2.1 on 2021-05-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
        ('laboratory', '0002_auto_20210529_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttestitem',
            name='handle_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_item_set', related_query_name='patient_test_items', to='his.staff', verbose_name='责任人'),
        ),
    ]
