# Generated by Django 3.1.7 on 2021-05-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_equipmentinfo_equipmentpurchase_equipmenttypeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentpurchase',
            name='quantity',
        ),
    ]
