# Generated by Django 3.1.7 on 2021-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_remove_equipmentpurchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinfo',
            name='purchase_date',
            field=models.DateField(auto_created=True, default='2021-05-09', editable=False, verbose_name='采购日期'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EquipmentPurchase',
        ),
    ]
