# Generated by Django 3.1.7 on 2021-05-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0008_auto_20210508_2307'),
        ('his', '0004_auto_20210509_1600'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_created=True, editable=False, verbose_name='挂号时间')),
                ('appointment_date', models.DateField(auto_created=True, editable=False, verbose_name='预约时间')),
                ('reg_id', models.PositiveIntegerField(unique=True, verbose_name='患者挂号')),
                ('reg_class', models.IntegerField(choices=[(0, '门诊'), (1, '急诊')], default=0, verbose_name='就诊类别')),
                ('illness_date', models.DateField(blank=True, verbose_name='患病日期')),
                ('chief_complaint', models.TextField(blank=True, max_length=512, verbose_name='患者主诉')),
                ('diagnosis_results', models.TextField(blank=True, max_length=512, verbose_name='确诊结果')),
                ('medical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_set', related_query_name='registrations', to='his.staff', verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_set', related_query_name='registrations', to='patient.patientuser', verbose_name='患者')),
            ],
            options={
                'verbose_name': '挂号信息',
                'verbose_name_plural': '挂号信息',
                'unique_together': {('patient', 'reg_id')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateTimeField(auto_created=True, editable=False, verbose_name='开具时间')),
                ('medicine_num', models.PositiveIntegerField(blank=True, verbose_name='药品种类数')),
                ('medical_advice', models.TextField(blank=True, max_length=400, null=True, verbose_name='医嘱')),
                ('payment_status', models.BooleanField(default=False, verbose_name='缴费状态')),
                ('registration_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_set', related_query_name='prescriptions', to='outpatient.registrationinfo', verbose_name='挂号信息')),
            ],
            options={
                'verbose_name': ('患者处方',),
                'verbose_name_plural': (('患者处方',),),
                'unique_together': {('registration_info', 'prescription_date')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.PositiveIntegerField(unique=True, verbose_name='细节编号')),
                ('medicine_quantity', models.PositiveIntegerField(verbose_name='药品数量')),
                ('medicine_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail_set', related_query_name='prescription_details', to='pharmacy.medicineinfo', verbose_name='药品信息')),
                ('prescription_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail_set', related_query_name='prescription_details', to='outpatient.prescription', verbose_name='处方')),
            ],
            options={
                'verbose_name': ('处方细节',),
                'verbose_name_plural': (('处方细节',),),
                'unique_together': {('prescription_info', 'detail_id')},
            },
        ),
    ]
