# Generated by Django 3.1.7 on 2021-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': '患者处方', 'verbose_name_plural': '患者处方'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondetail',
            options={'verbose_name': '处方细节', 'verbose_name_plural': '处方细节'},
        ),
    ]
