# Generated by Django 3.1.7 on 2021-05-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpatient', '0001_initial'),
        ('his', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleRegisterNumber',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='his.hospitaltitle', verbose_name='职称')),
                ('register_number', models.PositiveIntegerField(verbose_name='挂号数限额')),
            ],
            options={
                'verbose_name': '职称-挂号数',
                'verbose_name_plural': '职称-挂号数',
            },
        ),
        migrations.AddField(
            model_name='remainingregistration',
            name='medical_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_registration_set', related_query_name='remaining_registrations', to='his.staff', verbose_name='剩余挂号数'),
        ),
        migrations.AddField(
            model_name='registrationinfo',
            name='medical_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_set', related_query_name='registrations', to='his.staff', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='registrationinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_set', related_query_name='registrations', to='patient.patientuser', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='medicine_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail_set', related_query_name='prescription_details', to='pharmacy.medicineinfo', verbose_name='药品信息'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='prescription_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail_set', related_query_name='prescription_details', to='outpatient.prescription', verbose_name='处方'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='registration_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_set', related_query_name='prescriptions', to='outpatient.registrationinfo', verbose_name='挂号信息'),
        ),
        migrations.AlterUniqueTogether(
            name='remainingregistration',
            unique_together={('medical_staff', 'register_date')},
        ),
        migrations.AlterUniqueTogether(
            name='registrationinfo',
            unique_together={('patient', 'reg_id')},
        ),
        migrations.AlterUniqueTogether(
            name='prescriptiondetail',
            unique_together={('prescription_info', 'detail_id')},
        ),
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together={('registration_info', 'prescription_date')},
        ),
    ]
