# Generated by Django 3.1.7 on 2021-05-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0005_dutyroster'),
        ('outpatient', '0002_auto_20210509_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleRegisterNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.PositiveIntegerField(verbose_name='挂号数限额')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='his.hospitaltitle', unique=True, verbose_name='职称')),
            ],
            options={
                'verbose_name': '职称-挂号数',
                'verbose_name_plural': '职称-挂号数',
            },
        ),
        migrations.CreateModel(
            name='RemainingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(verbose_name='挂号日期')),
                ('remain_quantity', models.PositiveIntegerField(blank=True, verbose_name='当日剩余挂号数')),
                ('medical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_registration_set', related_query_name='remaining_registrations', to='his.staff', unique=True, verbose_name='剩余挂号数')),
            ],
            options={
                'verbose_name': '医生剩余挂号数',
                'unique_together': {('medical_staff', 'register_date')},
            },
        ),
    ]
