# Generated by Django 3.2.1 on 2021-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0002_auto_20210529_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinfo',
            name='diagnosis_state',
            field=models.IntegerField(choices=[(0, '待诊'), (1, '诊中'), (2, '完毕')], default=0, verbose_name='诊疗状态'),
        ),
    ]
