# Generated by Django 3.1.7 on 2021-05-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0002_auto_20210519_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfo',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='通过网页预约挂号的时间', verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='chief_complaint',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='患者主诉'),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='diagnosis_results',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='确诊结果'),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='illness_date',
            field=models.DateField(blank=True, null=True, verbose_name='患病日期'),
        ),
    ]
