# Generated by Django 3.1.7 on 2021-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0002_auto_20210516_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='detail_id',
            field=models.PositiveIntegerField(verbose_name='细节编号'),
        ),
    ]
