# Generated by Django 3.1.7 on 2021-05-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0003_auto_20210520_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfo',
            name='chief_complaint',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='患者主诉'),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='diagnosis_results',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='确诊结果'),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='illness_date',
            field=models.DateField(blank=True, null=True, verbose_name='患病日期'),
        ),
    ]
