# Generated by Django 3.1.7 on 2021-05-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0005_dutyroster'),
        ('outpatient', '0003_remainingregistration_titleregisternumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingregistration',
            name='medical_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_registration_set', related_query_name='remaining_registrations', to='his.staff', verbose_name='剩余挂号数'),
        ),
        migrations.AlterField(
            model_name='titleregisternumber',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='his.hospitaltitle', verbose_name='职称'),
        ),
    ]
