# Generated by Django 3.1.7 on 2021-06-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0004_registrationinfo_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationinfo',
            name='payment_status',
        ),
    ]
