# Generated by Django 3.1.7 on 2021-06-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0007_auto_20210605_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titleregisternumber',
            old_name='register_number',
            new_name='registration_number',
        ),
    ]
