# Generated by Django 3.1.7 on 2021-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(default=10, verbose_name='科室部门编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='科室部门名称'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_num',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
    ]
