# Generated by Django 3.1.7 on 2021-05-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='medical_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_set', related_query_name='duty_rosters', to='his.staff', verbose_name='医务人员'),
        ),
    ]
