# Generated by Django 3.1.7 on 2021-05-20 01:08

from django.db import migrations
import his.models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
                ('objects', his.models.StaffManager()),
            ],
        ),
    ]
