# Generated by Django 3.1.7 on 2021-04-26 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.usergroup', verbose_name='科室部门'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录信息'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.usergroup', verbose_name='科室部门'),
        ),
    ]
