# Generated by Django 3.1.7 on 2021-05-15 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptAreaBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_id', models.PositiveIntegerField(help_text='指定病区的第 n 个病床。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='床位号')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_set', related_query_name='areas', to='his.inpatientarea', verbose_name='病区')),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_set', related_query_name='depts', to='his.department', verbose_name='科室')),
            ],
            options={
                'verbose_name': '科室-病区-床位',
                'verbose_name_plural': '科室-病区-床位',
                'unique_together': {('dept', 'area', 'bed_id')},
            },
        ),
    ]
