# Generated by Django 3.1.7 on 2021-05-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_dept',
            field=models.ManyToManyField(related_name='notice_set_recv', related_query_name='notices_recv', to='his.Department', verbose_name='目标科室部门'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_set_send', related_query_name='notices_send', to='his.department', verbose_name='科室部门'),
        ),
    ]
