# Generated by Django 3.1.7 on 2021-05-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0002_auto_20210426_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='通知正文')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_dept', to='his.department', verbose_name='科室部门')),
            ],
            options={
                'verbose_name': '部门通知',
                'verbose_name_plural': '部门通知',
                'unique_together': {('dept', 'send_time')},
            },
        ),
    ]
