# Generated by Django 3.1.7 on 2021-04-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_usergroup_url_permissions'),
        ('his', '0002_auto_20210423_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.usergroup', verbose_name='科室部门'),
        ),
    ]
