# Generated by Django 3.1.7 on 2021-05-15 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0002_deptareabed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptareabed',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_set', related_query_name='depts', to='his.department', verbose_name='科室'),
        ),
    ]
