# Generated by Django 3.1.7 on 2021-03-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permgroup_create_time'),
        ('his', '0002_auto_20210320_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.userinfo', verbose_name='登录信息'),
        ),
    ]
