# Generated by Django 3.1.7 on 2021-04-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_usergroup_url_permissions'),
        ('his', '0003_staff_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='简介')),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.usergroup', verbose_name='科室部门')),
            ],
            options={
                'verbose_name': '科室部门',
                'verbose_name_plural': '科室部门',
            },
        ),
    ]
