# Generated by Django 3.1.7 on 2021-05-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0004_auto_20210509_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_day', models.PositiveIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], verbose_name='工作日')),
                ('duty_area', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='负责病区')),
                ('medical_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_set', related_query_name='duty_rosters', to='his.staff', verbose_name='医务人员')),
            ],
            options={
                'verbose_name': '医务人员排班表',
                'unique_together': {('medical_staff', 'working_day')},
            },
        ),
    ]
